object Versions {

    const val gradle = "7.2.2"
    const val kotlin = "1.7.10"
    const val kotlinCoroutine = "1.4.0"
    const val coRoutineAdapter = "0.9.2"
    const val navigation = "2.3.5"

    const val coreKTX = "1.3.2"
    const val appCompat = "1.2.0"
    const val constraintLayout = "2.0.4"
    const val fragmentKTX = "1.4.1"
    const val material = "1.1.0"

    const val composeActivities = "1.5.1"
    const val composeMaterialDesign = "1.2.1"
    const val composeAnimations = "1.2.1"
    const val composeTooling = "1.2.1"
    const val composeViewModels = "2.5.1"
    const val composeUITests = "1.2.1"

    const val archLifeCycle = "2.4.0"
    const val archLifeCycleExt = "2.2.0"
    const val gson = "2.8.6"
    const val retrofit = "2.9.0"
    const val recyclerView = "1.1.0"
    const val cardView = "1.0.0"
    const val support = "1.0.0"
    const val dagger = "2.43.2"
    const val okHttp3 = "4.4.0"
    const val picasso = "2.71828"
    
    const val androidxTest = "1.4.0"
    const val jUnit = "4.12"
    const val extJUnit = "1.1.3"
    const val espresso = "3.2.0"
    const val mockito = "3.7.7"
    const val archCore = "2.1.0"
    const val hamcrest = "2.2"
    const val googleTruth = "1.1.2"
    const val mockk = "1.10.0"

    const val robolectric = "4.5"
    const val robolectricShadows = "4.5"
    const val kotlinCoroutineTest = "1.4.2"
    const val nhaarmanMockito = "2.2.0"
    const val okHttpMockServer = "4.7.2"
}